id: ''
gist: ''
source: WEB
author: Microsoft
name: 'Blank snippet'
description: Create a new snippet from a blank template.
script:
  content: |-
    $("#run").click(run);

    function run() {
        console.log("Your code goes here");
    }
  language: typescript
style:
  content: /* Your style goes here */
  language: css
template:
  content: |-
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run</span>
    </button>
  language: html
libraries: |-
  // NPM libraries
  jquery
  office-ui-fabric-js/dist/js/fabric.min.js
  office-ui-fabric-js/dist/css/fabric.min.css
  office-ui-fabric-js/dist/css/fabric.components.min.css
  @microsoft/office-js-helpers/dist/office.helpers.min.js
  core-js/client/core.min.js

  // IntelliSense: Use dt~library_name for DefinitelyTyped or URLs to d.ts files
  dt~office-js
  dt~jquery
  dt~core-js
  @microsoft/office-js-helpers/dist/office.helpers.d.ts
