id: web_web_default
name: Blank snippet
description: Create a new snippet from a blank template.
author: Microsoft
host: WEB
api_set: {}
script:
    content: |
        $("#run").click(run);

        function run() {
            console.log("Your code goes here");
        }
    language: typescript
template:
    content: |
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Run</span>
        </button>
    language: html
style:
    content: "/* Your style goes here */\r\n"
    language: css
libraries: |
    # CSS Libraries
    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css

    # NPM libraries
    core-js@2.4.1/client/core.min.js
    @microsoft/office-js-helpers@0.5.0/dist/office.helpers.min.js
    jquery@3.1.1

    # IntelliSense: @types/library or node_modules paths or URL to d.ts files
    @types/core-js
    @microsoft/office-js-helpers/dist/office.helpers.d.ts
    @types/jquery
